version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  buildpack_deps:
    docker:
      - image: circleci/node

jobs:
  deploy_ghpages:
    executor: buildpack_deps
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - gh-pages/deploy:
          ssh-fingerprints: '62:c3:de:7c:94:10:58:b7:ee:ff:41:a2:81:e9:31:ed'
          build-dir: dist

workflows:
  build_deploy:
    jobs:
      - deploy_ghpages:
          filters:
            branches:
              only:
                - master
